/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Forest Katsch (https://sketchfab.com/ForestKatsch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spacex-dragon-2-exterior-2575398db20c406cab2cf72b89a9be8b
Title: SpaceX Dragon 2 exterior
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.draco_thruster} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.grey_plastic} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.ground} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.shiny_metal} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.windows} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.heatshield} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.trunk} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
