/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Thomas Flynn (https://sketchfab.com/nebulousflynn)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/planet-mars-nasa-mars-landing-2021-f735027736264c41b980193ee0aaf651
Title: Planet Mars - NASA Mars Landing 2021
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Model(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  const marsRef = useRef(null);
  useFrame(({ clock }) => {
    marsRef.current.rotation.y = clock.getElapsedTime() / 15;
  });
  return (
    <group ref={marsRef} scale={[2.5, 2.5, 2.5]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["Default_OBJ.005"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
